const getRecommendation = {
    "message": "success",
    "data": {
        "user_details": {
            "id": 6,
            "first_name": "Adeoluwa",
            "last_name": "Akinsanya",
            "user_id": "adeoluwa.akinsanya.71",
            "user_name": "akinsanyaadeoluwa31@gmail.com",
            "email": "",
            "phone": "08139354433",
            "age_range": "",
            "address": "",
            "profession": "Engineer",
            "employment_type": "Remote",
            "educational_qualification": "Bachelor's Degree",
            "minimum_salary": 0,
            "state": "Lagos",
            "lga": "Surulere",
            "token": "",
            "active": 1,
            "profile_image": "User_DP.png",
            "background_image": "",
            "text_colour": "#2FC341",
            "gender": "",
            "marital_status": "",
            "preferred_job_location_lga": "",
            "preferred_job1": "",
            "preferred_job2": "",
            "preferred_job3": "",
            "preferred_job4": "",
            "other_professions1": "",
            "other_professions2": "",
            "other_professions3": "",
            "other_professions4": "",
            "availability_start_date": null,
            "current_employer": "",
            "disabled": "",
            "languages1": "",
            "languages2": "",
            "languages3": "",
            "languages4": "",
            "languages5": "",
            "preferred_job_location_state": "",
            "cookie": "",
            "remember_token": null,
            "created_at": "2021-05-22T14:26:33.000000Z",
            "updated_at": "2021-05-22T14:28:46.000000Z"
        },
        "user_experiences": [],
        "sent_recommendation_requests": [
            {
                "id": 1,
                "sender_id": "adeoluwa.akinsanya.71",
                "sender_name": "Adeoluwa Akinsanya",
                "sender_job_title": "Engineer",
                "sender_company": "",
                "receiver_id": "adeoluwa.akinsanya",
                "receiver_name": "Adeoluwa Akinsanya",
                "receiver_job_title": "Software Engineer",
                "receiver_company": "",
                "subject": "I Will Like To Request A Recommendation From You",
                "message": "Kindly recommend me",
                "relationship": "Colleague",
                "relationship-position": "Engineer",
                "receiver_pic": "-",
                "sender_pic": "-",
                "accepted": -1,
                "created_at": "2021-05-25T12:46:48.000000Z",
                "updated_at": "2021-05-25T13:08:49.000000Z"
            }
        ],
        "sent_count": 1,
        "received_recommendation_requests": [
            {
                "id": 1,
                "sender_id": "adeoluwa.akinsanya.71",
                "sender_name": "Adeoluwa Akinsanya",
                "sender_job_title": "Engineer",
                "sender_company": "",
                "receiver_id": "adeoluwa.akinsanya",
                "receiver_name": "Adeoluwa Akinsanya",
                "receiver_job_title": "Software Engineer",
                "receiver_company": "",
                "subject": "I Will Like To Request A Recommendation From You",
                "message": "Kindly recommend me",
                "relationship": "Colleague",
                "relationship-position": "Engineer",
                "receiver_pic": "-",
                "sender_pic": "-",
                "accepted": -1,
                "created_at": "2021-05-25T12:46:48.000000Z",
                "updated_at": "2021-05-25T13:08:49.000000Z"
            }
        ],
        "received_count": 1,
        "sent_recommendation_offers": [
            {
                "id": 1,
                "sender_id": "adeoluwa.akinsanya.71",
                "sender_name": "Adeoluwa Akinsanya",
                "sender_job_title": "Engineer",
                "receiver_id": "adeoluwa.akinsanya",
                "receiver_name": "Adeoluwa Akinsanya",
                "receiver_job_title": "Software Engineer",
                "subject": "I Will Like To Recommend You",
                "message": "Test",
                "relationship": "Colleague",
                "relationship-position": "Engineer",
                "accepted": -1,
                "created_at": "2021-05-25T13:19:39.000000Z",
                "updated_at": "2021-05-25T13:20:42.000000Z"
            }
        ],
        "received_recommendation_offers": [
            {
                "id": 1,
                "sender_id": "adeoluwa.akinsanya.71",
                "sender_name": "Adeoluwa Akinsanya",
                "sender_job_title": "Engineer",
                "sender_company": "",
                "receiver_id": "adeoluwa.akinsanya",
                "receiver_name": "Adeoluwa Akinsanya",
                "receiver_job_title": "Software Engineer",
                "receiver_company": "",
                "subject": "I Will Like To Request A Recommendation From You",
                "message": "Kindly recommend me",
                "relationship": "Colleague",
                "relationship-position": "Engineer",
                "receiver_pic": "-",
                "sender_pic": "-",
                "accepted": -1,
                "created_at": "2021-05-25T12:46:48.000000Z",
                "updated_at": "2021-05-25T13:08:49.000000Z"
            }
        ]
    }
}

export default getRecommendation;